object Plugins {
    const val ANDROID_APPLICATION = "com.android.application"
    const val ANDROID_LIBRARY = "com.android.library"
    const val JAVA_LIBRARY = "java-library"
    const val JAVA_TEST_FIXTURES = "java-test-fixtures"
    const val CHECK_DEPENDENCY_UPDATES = "name.remal.check-dependency-updates"
    const val KOTLIN = "kotlin"
    const val KOTLIN_ANDROID = "kotlin-android"
    const val KOTLIN_KAPT = "kotlin-kapt"
    const val KOTLIN_PARCELIZE = "kotlin-parcelize"
    const val KOTLIN_SERIALIZATION = "org.jetbrains.kotlin.plugin.serialization"
    const val HILT_ANDROID = "dagger.hilt.android.plugin"
    const val GOOGLE_SERVICES = "com.google.gms.google-services"
    const val NAVIGATION_SAFEARGS = "androidx.navigation.safeargs.kotlin"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase.crashlytics"
    const val LICENSE = "com.jaredsburrows.license"
}