object Plugins {
    const val ANDROID_APPLICATION = "com.android.application"
    const val ANDROID_LIBRARY = "com.android.library"
    const val JAVA_LIBRARY = "java-library"
    const val CHECK_DEPENDENCY_UPDATES = "name.remal.check-dependency-updates"
    const val KOTLIN = "kotlin"
    const val KOTLIN_ANDROID = "kotlin-android"
    const val KOTLIN_ANDROID_EXTENSIONS = "kotlin-android-extensions"
    const val KOTLIN_KAPT = "kotlin-kapt"
    const val HILT_ANDROID = "dagger.hilt.android.plugin"
    const val GOOGLE_SERVICES = "com.google.gms.google-services"
    const val GMS_OSS_LICENSES = "com.google.android.gms.oss-licenses-plugin"
    const val NAVIGATION_SAFEARGS = "androidx.navigation.safeargs.kotlin"
    const val FIREBASE_CRASHLYTICS = "com.google.firebase.crashlytics"
}